general.import = ["/home/dmitry/.config/alacritty/themes/rose-pine.toml"]

[font]
size = 13.0

[font.bold]
family = "Iosevka Comfy"
style = "Bold"

[font.bold_italic]
family = "Iosevka Comfy"
style = "Bold Italic"

[font.italic]
family = "Iosevka Comfy"
style = "Italic"

[font.normal]
family = "Iosevka Comfy"
style = "Regular"

[window.padding]
x = 4
y = 4
