general.import = ["/home/dmitry/.config/alacritty/themes/dracula.toml"]

[font]
size = 12.0

[font.bold]
family = "Aporetic Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Aporetic Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Aporetic Sans Mono"
style = "Italic"

[font.normal]
family = "Aporetic Sans Mono"
style = "Regular"

[window.padding]
x = 4
y = 4
